---
title: "Getting and Cleaning Data Final Project Codebook"
author: "Viswathish Dinesh"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Codebook

This document is the codebook for this project. It gives details on how the data is retrieved, how it is manipulated, and explains the variables and transformations executed in the script.

## Retrieving the data

The data is retrieved from this link: (https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

The script automatically downloads the data to a subdirectory in the project folder. It also checks to see if the data is already downloaded to avoid multiple downloads, in case the script is ran multiple times. The data is then unzipped so that R can read it in.

## Processing Part 1: Reading the files into R/RStudio

The relevant data files are read into R using the read.table() function. The files are named:
X_train.txt
y_train.txt
subject_train.txt
X_test.txt
y_test.txt
subject_test.txt
activity_labels.txt
features.txt

The files are stored in variables with the same names as the text files, ready to begin sorting and processing.

## Processing Part 2: Assigning labels to variables
(Note: The process for testing and training data is identical. Only one is mentioned for brevity)
Readable column names are assigned to 'x_test', 'y_test', and 'subject_test'. 'y_test' and 'subject_test' are simply named for the ID which they represent, while the column names for 'x_test' are retrieved from the second column of 'features'.

## Processing Part 3: Merging separated data into one complete data set
The testing and training data are first individually merged into their own unified data tables, with 'y_test', or the activityID, placed in the first column, followed by 'subject_test', or subjectID. This is then followed by the data stored in 'x_test', containing the measurements for all of the features. The same process applies to the training data set with their respective values. The datasets are merged using the cbind() function, producing 'train_all' and 'test_all'.

Then, since the column names are identical between the two data sets, they are combined using the rbind() function, appending all of the rows of one data table to the other, creating a single data table containing all of the testing and training data, properly labeled, as requested by the project.

## Extract mean and SD values
Using the grepl() function, all column names containing "mean" or "std" were selected out of 'complete_data', the completely merged data set. The function call included the names 'activityID' and 'subjectID' in order to preserve the IDs of the respective values.

## Assigning descriptive labels for 'activityID'
At this point in time, 'activityID' only consists of numbers indicating the activity. This step replaces 'activityID' with a more descriptive activity name from the 'activity_labels' element.

The column name of the data table is also changed to 'activity', as it is no longer an ID number.

## Assigning descriptive variable names
Variable names are currently shortened to some arbitrary value. This step extends all variable names to contain the full name of each variable described in the column name. This allows for better readability by future users of the data, and fulfills another step of the project requirements.

## Creating a new tidy data set with averages of each variable
The final step of the project is to create a separate, independent, tidy data set containing the average of each variable by activity and subject. This step uses the 'group_by()' and 'summarize_all()' functions to group the table by activity and subject, then calculate the means of each column, respectively, and store the final value in a new dataset. The new dataset is then written to a file in order to be accessible without the use of R/RStudio.